import RequestProject.Cob2NormalForm
import Mathlib.Data.Fintype.EquivFin

/-!
# Composition of component-and-genus surface codes

This file constructs the finite gluing graph used to compose the
component-and-genus codes from `Cob2NormalForm`.

For codes `s : a → b` and `t : b → c`, the vertices are the components of
`s` and `t`.  Every middle boundary circle is retained as a separately
indexed edge, so parallel gluings are not collapsed.  Resulting components
are the equivalence classes generated by the endpoints of these edges.
Their genus is

`old genera + number of middle edges - number of old components + 1`.

This is a combinatorial composition candidate.  No associativity,
normal-form completeness, or comparison with geometric cobordisms is
claimed here.
-/

open scoped BigOperators

noncomputable section

namespace Cob2NormalForm

namespace SurfaceCode

variable {a b c : ℕ} (s : SurfaceCode a b) (t : SurfaceCode b c)

/-- Vertices of the bipartite gluing graph: a component of the first code
or a component of the second code. -/
abbrev GlueVertex :=
  Fin s.ncomp ⊕ Fin t.ncomp

/-- The indexed endpoints of a middle boundary circle.  The index itself is
kept separately below, so distinct middle circles can give parallel edges. -/
def edgeEnds (i : Fin b) : GlueVertex s t × GlueVertex s t :=
  (Sum.inl (s.outComp i), Sum.inr (t.inComp i))

/-- The generating adjacency relation of the gluing graph. -/
def GlueStep (x y : GlueVertex s t) : Prop :=
  ∃ i : Fin b, (x, y) = edgeEnds s t i

/-- Connectedness in the gluing graph, as the equivalence closure of its
oriented generating edges. -/
def glueSetoid : Setoid (GlueVertex s t) :=
  Relation.EqvGen.setoid (GlueStep s t)

/-- A resulting connected component of a gluing. -/
abbrev GlueComponent :=
  Quotient (glueSetoid s t)

local instance glueComponentFintype : Fintype (GlueComponent s t) := by
  classical
  infer_instance

/-- The component containing a vertex. -/
def vertexComponent (v : GlueVertex s t) : GlueComponent s t :=
  Quotient.mk (glueSetoid s t) v

/-- The two endpoints of every retained middle edge lie in the same
resulting component. -/
theorem edgeEnds_same_component (i : Fin b) :
    vertexComponent s t (Sum.inl (s.outComp i)) =
      vertexComponent s t (Sum.inr (t.inComp i)) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _
    ⟨i, rfl⟩

/-- Number of old component vertices in a resulting component. -/
def vertexCount (q : GlueComponent s t) : ℕ :=
  Nat.card {v : GlueVertex s t // vertexComponent s t v = q}

/-- Number of indexed middle edges in a resulting component.  Counting
indices rather than adjacent vertex pairs preserves parallel edges. -/
def edgeCount (q : GlueComponent s t) : ℕ :=
  Nat.card {i : Fin b //
    vertexComponent s t (Sum.inl (s.outComp i)) = q}

/-- Sum of the genera carried by all old vertices in one resulting
component. -/
def oldGenus (q : GlueComponent s t) : ℕ :=
  by
    classical
    exact
      (∑ i : Fin s.ncomp,
          if vertexComponent s t (Sum.inl i) = q then s.genus i else 0) +
        ∑ j : Fin t.ncomp,
          if vertexComponent s t (Sum.inr j) = q then t.genus j else 0

/-- Genus of a resulting component.  The `Nat` subtraction is the first
Betti-number contribution of the connected finite multigraph. -/
def gluedGenus (q : GlueComponent s t) : ℕ :=
  oldGenus s t q + edgeCount s t q + 1 - vertexCount s t q

/-- A finite-type presentation of surface code data, prior to choosing
numeric component labels. -/
structure FiniteCode (a c : ℕ) where
  Component : Type
  fintypeComponent : Fintype Component
  inComp : Fin a → Component
  outComp : Fin c → Component
  genus : Component → ℕ

attribute [instance] FiniteCode.fintypeComponent

/-- Replace an arbitrary finite component type by canonical `Fin` labels. -/
def FiniteCode.toSurfaceCode (u : FiniteCode a c) : SurfaceCode a c where
  ncomp := Fintype.card u.Component
  inComp := Fintype.equivFin u.Component ∘ u.inComp
  outComp := Fintype.equivFin u.Component ∘ u.outComp
  genus := u.genus ∘ (Fintype.equivFin u.Component).symm

/-- Equivalent finite component presentations give relabel-equivalent
surface codes. -/
theorem FiniteCode.rel_toSurfaceCode
    (u v : FiniteCode a c)
    (e : u.Component ≃ v.Component)
    (hin : ∀ i, e (u.inComp i) = v.inComp i)
    (hout : ∀ j, e (u.outComp j) = v.outComp j)
    (hgenus : ∀ q, v.genus (e q) = u.genus q) :
    Rel u.toSurfaceCode v.toSurfaceCode := by
  let eFin : Fin (Fintype.card u.Component) ≃
      Fin (Fintype.card v.Component) :=
    (Fintype.equivFin u.Component).symm.trans
      (e.trans (Fintype.equivFin v.Component))
  refine ⟨eFin, ?_, ?_, ?_⟩
  · intro i
    simp [FiniteCode.toSurfaceCode, eFin, hin]
  · intro j
    simp [FiniteCode.toSurfaceCode, eFin, hout]
  · intro k
    simp [FiniteCode.toSurfaceCode, eFin, hgenus]

/-- The finite component presentation supplied by the gluing graph. -/
def glueFiniteCode : FiniteCode a c where
  Component := GlueComponent s t
  fintypeComponent := glueComponentFintype s t
  inComp := fun i => vertexComponent s t (Sum.inl (s.inComp i))
  outComp := fun j => vertexComponent s t (Sum.inr (t.outComp j))
  genus := gluedGenus s t

/-- Composition of representatives, with component labels chosen only after
forming the connected-component quotient. -/
def comp : SurfaceCode a c :=
  (glueFiniteCode s t).toSurfaceCode

section Relabeling

variable {s s' : SurfaceCode a b} {t t' : SurfaceCode b c}

/-- Relabel both sides of the bipartite gluing graph. -/
def vertexRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp) :
    GlueVertex s t ≃ GlueVertex s' t' :=
  Equiv.sumCongr e f

private theorem glueStep_map
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    {x y : GlueVertex s t}
    (h : GlueStep s t x y) :
    GlueStep s' t' (vertexRelabel e f x) (vertexRelabel e f y) := by
  rcases h with ⟨i, h⟩
  have hx : x = Sum.inl (s.outComp i) := congrArg Prod.fst h
  have hy : y = Sum.inr (t.inComp i) := congrArg Prod.snd h
  subst x
  subst y
  refine ⟨i, ?_⟩
  simp [edgeEnds, vertexRelabel, eout, fin]

private theorem glueConnected_map
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    {x y : GlueVertex s t}
    (h : (glueSetoid s t) x y) :
    (glueSetoid s' t') (vertexRelabel e f x) (vertexRelabel e f y) := by
  change Relation.EqvGen (GlueStep s t) x y at h
  change Relation.EqvGen (GlueStep s' t')
    (vertexRelabel e f x) (vertexRelabel e f y)
  induction h with
  | rel x y hxy =>
      exact Relation.EqvGen.rel _ _
        (glueStep_map e f eout fin hxy)
  | refl x =>
      exact Relation.EqvGen.refl _
  | symm x y _ ih =>
      exact Relation.EqvGen.symm _ _ ih
  | trans x y z _ _ ihxy ihyz =>
      exact Relation.EqvGen.trans _ _ _ ihxy ihyz

/-- Component quotient equivalence induced by relabeling the two input
codes. -/
def componentRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i) :
    GlueComponent s t ≃ GlueComponent s' t' where
  toFun := Quotient.map' (vertexRelabel e f)
    (fun _ _ h => glueConnected_map e f eout fin h)
  invFun := Quotient.map' (vertexRelabel e.symm f.symm)
    (fun _ _ h => glueConnected_map e.symm f.symm
      (fun i => by simpa using congrArg e.symm (eout i).symm)
      (fun i => by simpa using congrArg f.symm (fin i).symm) h)
  left_inv := by
    intro q
    induction q using Quotient.inductionOn with
    | _ x => simp [vertexRelabel]
  right_inv := by
    intro q
    induction q using Quotient.inductionOn with
    | _ x => simp [vertexRelabel]

@[simp]
theorem componentRelabel_vertexComponent
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (x : GlueVertex s t) :
    componentRelabel e f eout fin (vertexComponent s t x) =
      vertexComponent s' t' (vertexRelabel e f x) :=
  by
    rfl

/-- Relabeling identifies the old-vertex fibers over corresponding
components. -/
def vertexFiberRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (q : GlueComponent s t) :
    {x : GlueVertex s t // vertexComponent s t x = q} ≃
      {x : GlueVertex s' t' //
        vertexComponent s' t' x = componentRelabel e f eout fin q} where
  toFun x :=
    ⟨vertexRelabel e f x.1, by
      rw [← componentRelabel_vertexComponent]
      exact congrArg (componentRelabel e f eout fin) x.2⟩
  invFun x :=
    ⟨vertexRelabel e.symm f.symm x.1, by
      apply (componentRelabel e f eout fin).injective
      rw [componentRelabel_vertexComponent]
      simpa [vertexRelabel] using x.2⟩
  left_inv x := by
    apply Subtype.ext
    simp [vertexRelabel]
  right_inv x := by
    apply Subtype.ext
    simp [vertexRelabel]

/-- Relabeling preserves the number of old vertices in each component. -/
theorem vertexCount_componentRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (q : GlueComponent s t) :
    vertexCount s' t' (componentRelabel e f eout fin q) =
      vertexCount s t q := by
  exact (Nat.card_congr (vertexFiberRelabel e f eout fin q)).symm

/-- Relabeling identifies the retained-middle-edge fibers over corresponding
components. -/
def edgeFiberRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (q : GlueComponent s t) :
    {i : Fin b //
      vertexComponent s t (Sum.inl (s.outComp i)) = q} ≃
      {i : Fin b //
        vertexComponent s' t' (Sum.inl (s'.outComp i)) =
          componentRelabel e f eout fin q} where
  toFun i :=
    ⟨i.1, by
      simpa [vertexRelabel, eout] using
        congrArg (componentRelabel e f eout fin) i.2⟩
  invFun i :=
    ⟨i.1, by
      apply (componentRelabel e f eout fin).injective
      simpa [vertexRelabel, eout] using i.2⟩
  left_inv i := rfl
  right_inv i := rfl

/-- Relabeling preserves the indexed middle-edge count in each component. -/
theorem edgeCount_componentRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (q : GlueComponent s t) :
    edgeCount s' t' (componentRelabel e f eout fin q) =
      edgeCount s t q := by
  exact (Nat.card_congr (edgeFiberRelabel e f eout fin q)).symm

/-- Relabeling preserves the sum of the genera on the old vertices. -/
theorem oldGenus_componentRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (egenus : ∀ k, s'.genus (e k) = s.genus k)
    (fgenus : ∀ k, t'.genus (f k) = t.genus k)
    (q : GlueComponent s t) :
    oldGenus s' t' (componentRelabel e f eout fin q) =
      oldGenus s t q := by
  classical
  have heq (i : Fin s.ncomp) :
      (vertexComponent s' t' (Sum.inl (e i)) =
          componentRelabel e f eout fin q) =
        (vertexComponent s t (Sum.inl i) = q) := by
    apply propext
    have hmap :
        componentRelabel e f eout fin
            (vertexComponent s t (Sum.inl i)) =
          vertexComponent s' t' (Sum.inl (e i)) := by
      simp [vertexRelabel]
    rw [← hmap]
    exact (componentRelabel e f eout fin).apply_eq_iff_eq
  have hfeq (j : Fin t.ncomp) :
      (vertexComponent s' t' (Sum.inr (f j)) =
          componentRelabel e f eout fin q) =
        (vertexComponent s t (Sum.inr j) = q) := by
    apply propext
    have hmap :
        componentRelabel e f eout fin
            (vertexComponent s t (Sum.inr j)) =
          vertexComponent s' t' (Sum.inr (f j)) := by
      simp [vertexRelabel]
    rw [← hmap]
    exact (componentRelabel e f eout fin).apply_eq_iff_eq
  unfold oldGenus
  rw [← e.sum_comp
    (fun i => if vertexComponent s' t' (Sum.inl i) =
      componentRelabel e f eout fin q then s'.genus i else 0)]
  rw [← f.sum_comp
    (fun j => if vertexComponent s' t' (Sum.inr j) =
      componentRelabel e f eout fin q then t'.genus j else 0)]
  simp only [heq, hfeq, egenus, fgenus]

/-- Relabeling preserves the complete gluing-genus formula. -/
theorem gluedGenus_componentRelabel
    (e : Fin s.ncomp ≃ Fin s'.ncomp)
    (f : Fin t.ncomp ≃ Fin t'.ncomp)
    (eout : ∀ i, e (s.outComp i) = s'.outComp i)
    (fin : ∀ i, f (t.inComp i) = t'.inComp i)
    (egenus : ∀ k, s'.genus (e k) = s.genus k)
    (fgenus : ∀ k, t'.genus (f k) = t.genus k)
    (q : GlueComponent s t) :
    gluedGenus s' t' (componentRelabel e f eout fin q) =
      gluedGenus s t q := by
  simp only [gluedGenus, oldGenus_componentRelabel e f eout fin egenus fgenus,
    edgeCount_componentRelabel e f eout fin,
    vertexCount_componentRelabel e f eout fin]

/-- Composition is invariant under independent relabeling of the two input
codes. -/
theorem rel_comp
    (hs : Rel s s') (ht : Rel t t') :
    Rel (comp s t) (comp s' t') := by
  rcases hs with ⟨e, ein, eout, egenus⟩
  rcases ht with ⟨f, fin, fout, fgenus⟩
  apply FiniteCode.rel_toSurfaceCode
    (glueFiniteCode s t) (glueFiniteCode s' t')
    (componentRelabel e f eout fin)
  · intro i
    simp [glueFiniteCode, vertexRelabel, ein]
  · intro j
    simp [glueFiniteCode, vertexRelabel, fout]
  · intro q
    exact gluedGenus_componentRelabel e f eout fin egenus fgenus q

end Relabeling

section ConnectedRegression

variable (a b c g h : ℕ)

private def fiberEquivOfSubsingleton
    {α β : Type} [Subsingleton β] (f : α → β) (q : β) :
    {x : α // f x = q} ≃ α where
  toFun := Subtype.val
  invFun := fun x => ⟨x, Subsingleton.elim _ _⟩
  left_inv := fun _ => rfl
  right_inv := fun _ => rfl

/-- Gluing two one-component codes along a nonempty middle boundary gives
one connected component. -/
theorem connected_glueComponent_subsingleton (hb : 0 < b) :
    Subsingleton
      (GlueComponent (connected a b g) (connected b c h)) := by
  let middle : Fin b := ⟨0, hb⟩
  have hedge :
      vertexComponent (connected a b g) (connected b c h)
          (Sum.inl (0 : Fin 1)) =
        vertexComponent (connected a b g) (connected b c h)
          (Sum.inr (0 : Fin 1)) := by
    simpa [connected] using
      edgeEnds_same_component (connected a b g) (connected b c h) middle
  have hvertex (x :
      GlueVertex (connected a b g) (connected b c h)) :
      vertexComponent (connected a b g) (connected b c h) x =
        vertexComponent (connected a b g) (connected b c h)
          (Sum.inl (0 : Fin 1)) := by
    rcases x with i | j
    · change Fin 1 at i
      congr 2
      exact Subsingleton.elim i (0 : Fin 1)
    · calc
        vertexComponent (connected a b g) (connected b c h) (Sum.inr j) =
            vertexComponent (connected a b g) (connected b c h)
              (Sum.inr (0 : Fin 1)) := by
                change Fin 1 at j
                congr 2
                exact Subsingleton.elim j (0 : Fin 1)
        _ = vertexComponent (connected a b g) (connected b c h)
              (Sum.inl (0 : Fin 1)) := hedge.symm
  constructor
  intro q r
  induction q using Quotient.inductionOn with
  | _ x =>
      induction r using Quotient.inductionOn with
      | _ y => exact (hvertex x).trans (hvertex y).symm

/-- The connected-component quotient in the positive-boundary regression
has exactly one element. -/
theorem connected_componentCard (hb : 0 < b) :
    Fintype.card
        (GlueComponent (connected a b g) (connected b c h)) =
      1 := by
  letI : Subsingleton
      (GlueComponent (connected a b g) (connected b c h)) :=
    connected_glueComponent_subsingleton a b c g h hb
  apply Fintype.card_eq_one_iff.mpr
  refine ⟨vertexComponent (connected a b g) (connected b c h)
    (Sum.inl (0 : Fin 1)), ?_⟩
  intro q
  exact Subsingleton.elim _ _

/-- A positive-boundary gluing of two connected codes has two old component
vertices. -/
theorem connected_vertexCount (hb : 0 < b)
    (q : GlueComponent (connected a b g) (connected b c h)) :
    vertexCount (connected a b g) (connected b c h) q = 2 := by
  letI : Subsingleton
      (GlueComponent (connected a b g) (connected b c h)) :=
    connected_glueComponent_subsingleton a b c g h hb
  let e := fiberEquivOfSubsingleton
    (fun x : GlueVertex (connected a b g) (connected b c h) =>
      vertexComponent (connected a b g) (connected b c h) x) q
  simpa [vertexCount, GlueVertex, connected] using Nat.card_congr e

/-- Every indexed middle circle belongs to the unique resulting component,
so parallel edges are counted with their full multiplicity `b`. -/
theorem connected_edgeCount (hb : 0 < b)
    (q : GlueComponent (connected a b g) (connected b c h)) :
    edgeCount (connected a b g) (connected b c h) q = b := by
  letI : Subsingleton
      (GlueComponent (connected a b g) (connected b c h)) :=
    connected_glueComponent_subsingleton a b c g h hb
  let e := fiberEquivOfSubsingleton
    (fun i : Fin b =>
      vertexComponent (connected a b g) (connected b c h)
        (Sum.inl ((connected a b g).outComp i))) q
  simpa [edgeCount] using Nat.card_congr e

/-- The old genus labels contribute exactly `g + h` in the connected
positive-boundary regression. -/
theorem connected_oldGenus (hb : 0 < b)
    (q : GlueComponent (connected a b g) (connected b c h)) :
    oldGenus (connected a b g) (connected b c h) q = g + h := by
  letI : Subsingleton
      (GlueComponent (connected a b g) (connected b c h)) :=
    connected_glueComponent_subsingleton a b c g h hb
  have hleft (i : Fin (connected a b g).ncomp) :
      vertexComponent (connected a b g) (connected b c h) (Sum.inl i) = q :=
    Subsingleton.elim _ _
  have hright (j : Fin (connected b c h).ncomp) :
      vertexComponent (connected a b g) (connected b c h) (Sum.inr j) = q :=
    Subsingleton.elim _ _
  unfold oldGenus
  simp only [if_pos (hleft _), if_pos (hright _)]
  simp [connected]

/-- The genus formula for a nonempty gluing of two one-component codes. -/
theorem connected_gluedGenus (hb : 0 < b)
    (q : GlueComponent (connected a b g) (connected b c h)) :
    gluedGenus (connected a b g) (connected b c h) q =
      g + (b - 1) + h := by
  simp only [gluedGenus, connected_oldGenus a b c g h hb,
    connected_edgeCount a b c g h hb,
    connected_vertexCount a b c g h hb]
  omega

/-- Representative-level positive-boundary connected composition. -/
theorem rel_comp_connected (hb : 0 < b) :
    Rel
      (comp (connected a b g) (connected b c h))
      (connected a c (g + (b - 1) + h)) := by
  let Q :=
    GlueComponent (connected a b g) (connected b c h)
  have hcard : Fintype.card Q = 1 :=
    connected_componentCard a b c g h hb
  let e : Fin (Fintype.card Q) ≃ Fin 1 := finCongr hcard
  refine ⟨e, ?_, ?_, ?_⟩
  · intro i
    change e _ = (0 : Fin 1)
    exact Subsingleton.elim _ _
  · intro j
    change e _ = (0 : Fin 1)
    exact Subsingleton.elim _ _
  · intro k
    change g + (b - 1) + h =
      gluedGenus (connected a b g) (connected b c h)
        ((Fintype.equivFin Q).symm k)
    exact (connected_gluedGenus a b c g h hb _).symm

end ConnectedRegression

end SurfaceCode

namespace SurfaceNF

/-- Composition descends from representatives because the gluing graph and
all of its counts are invariant under component relabeling. -/
def comp {a b c : ℕ} (s : SurfaceNF a b) (t : SurfaceNF b c) :
    SurfaceNF a c :=
  Quotient.map₂ SurfaceCode.comp
    (fun _ _ hs _ _ ht => SurfaceCode.rel_comp hs ht) s t

@[simp]
theorem comp_mk {a b c : ℕ}
    (s : SurfaceCode a b) (t : SurfaceCode b c) :
    comp
        (Quotient.mk (SurfaceCode.setoid a b) s)
        (Quotient.mk (SurfaceCode.setoid b c) t) =
      Quotient.mk (SurfaceCode.setoid a c) (SurfaceCode.comp s t) :=
  rfl

/-- Gluing two connected codes along at least one middle boundary circle
adds the graph-cycle contribution `b - 1` to the genus. -/
theorem comp_connected (a b c g h : ℕ) (hb : 0 < b) :
    comp (connected a b g) (connected b c h) =
      connected a c (g + (b - 1) + h) := by
  apply Quotient.sound
  exact SurfaceCode.rel_comp_connected a b c g h hb

end SurfaceNF

end Cob2NormalForm
