import RequestProject.Cob2Monoidal

open CategoryTheory MonoidalCategory

noncomputable section

/-!
# The symmetric monoidal quotient of the algebraic Cob2 presentation

This is a fresh wrapper around arities.  Its braiding is represented by the existing raw
`Cob2Mor.swap` word.  The construction is algebraic: no normal-form, universal-property, or
identification with geometric oriented bordisms is asserted.
-/

@[ext] structure Cob2SymmetricObj where
  arity : ℕ

/-- Raw inverse-associator transport. -/
def cob2αmInv (a b c : ℕ) : Cob2Mor (a + (b + c)) ((a + b) + c) :=
  Cob2Mor.eqToMor (Nat.add_assoc a b c).symm

/-- The monoidal relation enlarged by swap naturality, involutivity, and both hexagons. -/
inductive Cob2SymmetricRel : {a b : ℕ} → Cob2Mor a b → Cob2Mor a b → Prop
  | monoidal {a b} {f g : Cob2Mor a b} : Cob2MonoidalRel f g → Cob2SymmetricRel f g
  | comp_congr {a b c} {f f' : Cob2Mor a b} {g g' : Cob2Mor b c} :
      Cob2SymmetricRel f f' → Cob2SymmetricRel g g' →
        Cob2SymmetricRel (.comp f g) (.comp f' g')
  | tensor_congr {a b c d} {f f' : Cob2Mor a b} {g g' : Cob2Mor c d} :
      Cob2SymmetricRel f f' → Cob2SymmetricRel g g' →
        Cob2SymmetricRel (.tensor f g) (.tensor f' g')
  | refl {a b} (f : Cob2Mor a b) : Cob2SymmetricRel f f
  | symm {a b} {f g : Cob2Mor a b} : Cob2SymmetricRel f g → Cob2SymmetricRel g f
  | trans {a b} {f g h : Cob2Mor a b} :
      Cob2SymmetricRel f g → Cob2SymmetricRel g h → Cob2SymmetricRel f h
  | swap_naturality {a b c d} (f : Cob2Mor a b) (g : Cob2Mor c d) :
      Cob2SymmetricRel
        (.comp (.tensor f g) (.swap b d))
        (.comp (.swap a c) (.tensor g f))
  | swap_involutive (a b : ℕ) :
      Cob2SymmetricRel (.comp (.swap a b) (.swap b a)) (.id (a + b))
  | hexagon_forward (a b c : ℕ) :
      Cob2SymmetricRel
        (.comp (.comp (cob2αm a b c) (.swap a (b + c))) (cob2αm b c a))
        (.comp (.comp (.tensor (.swap a b) (.id c)) (cob2αm b a c))
          (.tensor (.id b) (.swap a c)))
  | hexagon_reverse (a b c : ℕ) :
      Cob2SymmetricRel
        (.comp (.comp (cob2αmInv a b c) (.swap (a + b) c)) (cob2αmInv c a b))
        (.comp (.comp (.tensor (.id a) (.swap b c)) (cob2αmInv a c b))
          (.tensor (.swap a c) (.id b)))

/-- The indexed setoid generated by the symmetric relation. -/
def Cob2SymmetricSetoid (a b : ℕ) : Setoid (Cob2Mor a b) where
  r := Cob2SymmetricRel
  iseqv := ⟨Cob2SymmetricRel.refl, Cob2SymmetricRel.symm, Cob2SymmetricRel.trans⟩

/-- Morphisms in the symmetric quotient. -/
def Cob2SymmetricHom (X Y : Cob2SymmetricObj) : Type :=
  Quotient (Cob2SymmetricSetoid X.arity Y.arity)

namespace Cob2Symmetric

private def qid (X : Cob2SymmetricObj) : Cob2SymmetricHom X X := ⟦Cob2Mor.id X.arity⟧

private def qcomp {X Y Z : Cob2SymmetricObj}
    (f : Cob2SymmetricHom X Y) (g : Cob2SymmetricHom Y Z) : Cob2SymmetricHom X Z :=
  Quotient.map₂ Cob2Mor.comp (fun _ _ hf _ _ hg => by
    change Cob2SymmetricRel _ _ at hf hg
    exact Cob2SymmetricRel.comp_congr hf hg) f g

instance category : Category Cob2SymmetricObj where
  Hom := Cob2SymmetricHom
  id := qid
  comp := qcomp
  id_comp f := by
    obtain ⟨f⟩ := f
    exact Quotient.sound (.monoidal (.old (.id_comp f)))
  comp_id f := by
    obtain ⟨f⟩ := f
    exact Quotient.sound (.monoidal (.old (.comp_id f)))
  assoc f g h := by
    obtain ⟨f⟩ := f
    obtain ⟨g⟩ := g
    obtain ⟨h⟩ := h
    exact Quotient.sound (.monoidal (.old (.assoc f g h)))

/-- Tensor on wrapped arities. -/
def tensorObj (X Y : Cob2SymmetricObj) : Cob2SymmetricObj := ⟨X.arity + Y.arity⟩

/-- Tensor on quotient morphisms. -/
def tensorHom {X₁ Y₁ X₂ Y₂ : Cob2SymmetricObj}
    (f : X₁ ⟶ Y₁) (g : X₂ ⟶ Y₂) : tensorObj X₁ X₂ ⟶ tensorObj Y₁ Y₂ :=
  Quotient.map₂ Cob2Mor.tensor
    (fun _ _ hf _ _ hg => by
      change Cob2SymmetricRel _ _ at hf hg
      exact Cob2SymmetricRel.tensor_congr hf hg) f g

/-- Named multiplication class. -/
def mul : (⟨2⟩ : Cob2SymmetricObj) ⟶ ⟨1⟩ := ⟦Cob2Mor.μ⟧
/-- Named unit class. -/
def unit : (⟨0⟩ : Cob2SymmetricObj) ⟶ ⟨1⟩ := ⟦Cob2Mor.η⟧
/-- Named comultiplication class. -/
def comul : (⟨1⟩ : Cob2SymmetricObj) ⟶ ⟨2⟩ := ⟦Cob2Mor.δ⟧
/-- Named counit class. -/
def counit : (⟨1⟩ : Cob2SymmetricObj) ⟶ ⟨0⟩ := ⟦Cob2Mor.ε⟧
/-- Named swap class only; no braiding is asserted. -/
def swap (a b : ℕ) : (⟨a + b⟩ : Cob2SymmetricObj) ⟶ ⟨b + a⟩ := ⟦Cob2Mor.swap a b⟧

private def assocEq (X Y Z : Cob2SymmetricObj) :
    tensorObj (tensorObj X Y) Z = tensorObj X (tensorObj Y Z) := by
  apply Cob2SymmetricObj.ext
  exact Nat.add_assoc _ _ _

private def leftEq (X : Cob2SymmetricObj) : tensorObj ⟨0⟩ X = X := by
  apply Cob2SymmetricObj.ext
  exact Nat.zero_add _

private def rightEq (X : Cob2SymmetricObj) : tensorObj X ⟨0⟩ = X := by
  apply Cob2SymmetricObj.ext
  exact Nat.add_zero _

instance monoidalStruct : MonoidalCategoryStruct Cob2SymmetricObj where
  tensorObj := tensorObj
  tensorHom := tensorHom
  whiskerLeft X _ _ f := tensorHom (𝟙 X) f
  whiskerRight f Y := tensorHom f (𝟙 Y)
  tensorUnit := ⟨0⟩
  associator X Y Z := eqToIso (assocEq X Y Z)
  leftUnitor X := eqToIso (leftEq X)
  rightUnitor X := eqToIso (rightEq X)

/-
A raw equality transport represents the categorical `eqToHom` of wrapped arities.
-/
theorem class_eqToMor {a b : ℕ} (h : a = b) :
    (⟦Cob2Mor.eqToMor h⟧ : (⟨a⟩ : Cob2SymmetricObj) ⟶ ⟨b⟩) =
      eqToHom (Cob2SymmetricObj.ext h) := by
        aesop

theorem associator_hom_class (X Y Z : Cob2SymmetricObj) :
    (α_ X Y Z).hom =
      (⟦cob2αm X.arity Y.arity Z.arity⟧ :
        tensorObj (tensorObj X Y) Z ⟶ tensorObj X (tensorObj Y Z)) := by
          convert rfl;
          convert class_eqToMor _

theorem leftUnitor_hom_class (X : Cob2SymmetricObj) :
    (λ_ X).hom =
      (⟦cob2Leftm X.arity⟧ : tensorObj ⟨0⟩ X ⟶ X) := by
        convert rfl;
        convert class_eqToMor _

theorem rightUnitor_hom_class (X : Cob2SymmetricObj) :
    (ρ_ X).hom =
      (⟦cob2Rightm X.arity⟧ : tensorObj X ⟨0⟩ ⟶ X) := by
        convert class_eqToMor _;
        exact Nat.add_zero _

/-
Tensoring two raw equality transports gives transport along addition.
-/
theorem tensor_eqToMor {a b c d : ℕ} (h : a = b) (k : c = d) :
    (⟦Cob2Mor.tensor (Cob2Mor.eqToMor h) (Cob2Mor.eqToMor k)⟧ :
      (⟨a + c⟩ : Cob2SymmetricObj) ⟶ ⟨b + d⟩) =
      eqToHom (Cob2SymmetricObj.ext (congrArg₂ (· + ·) h k)) := by
        have h_tensor_id : Cob2SymmetricRel (Cob2Mor.tensor (Cob2Mor.eqToMor h) (Cob2Mor.eqToMor k)) (Cob2Mor.eqToMor (by
        rw [ h, k ])) := by
          all_goals generalize_proofs at *;
          induction h ; induction k ; simp_all +decide [ Cob2Mor.eqToMor ];
          exact .monoidal (.tensor_id a c)
        generalize_proofs at *;
        exact Quotient.sound h_tensor_id |> fun h => h.trans ( by aesop )

private theorem tensorHom_eqToHom
    {X X' Y Y' : Cob2SymmetricObj} (h : X = X') (k : Y = Y') :
    tensorHom (eqToHom h) (eqToHom k) =
      eqToHom (congrArg₂ tensorObj h k) := by
        unfold eqToHom tensorHom;
        convert tensor_eqToMor _ _;
        rotate_left;
        exact congr_arg Cob2SymmetricObj.arity h;
        exact congr_arg Cob2SymmetricObj.arity k;
        unfold Quotient.map₂; aesop;

private theorem pentagon_transport (W X Y Z : Cob2SymmetricObj) :
    tensorHom (eqToIso (assocEq W X Y)).hom (𝟙 Z) ≫
        (eqToIso (assocEq W (tensorObj X Y) Z)).hom ≫
          tensorHom (𝟙 W) (eqToIso (assocEq X Y Z)).hom =
      (eqToIso (assocEq (tensorObj W X) Y Z)).hom ≫
        (eqToIso (assocEq W X (tensorObj Y Z))).hom := by
          simp +decide [ eqToIso, CategoryTheory.eqToHom_trans ];
          grind +suggestions

private theorem triangle_transport (X Y : Cob2SymmetricObj) :
    (eqToIso (assocEq X ⟨0⟩ Y)).hom ≫ tensorHom (𝟙 X) (eqToIso (leftEq Y)).hom =
      tensorHom (eqToIso (rightEq X)).hom (𝟙 Y) := by
        convert tensorHom_eqToHom _ _ using 1;
        all_goals norm_num [ eqToIso, eqToHom ];
        · grind +locals;
        · convert tensorHom_eqToHom rfl rfl using 1;
        · exact Cob2SymmetricObj.ext ( Nat.add_zero _ )

/-- The lawful monoidal category on the strengthened quotient. -/
instance cob2MonoidalCategory : MonoidalCategory Cob2SymmetricObj :=
  MonoidalCategory.ofTensorHom
    (id_tensorHom_id := by
      intro X Y
      exact Quotient.sound (.monoidal (.tensor_id X.arity Y.arity)))
    (id_tensorHom := by intros; rfl)
    (tensorHom_id := by intros; rfl)
    (tensorHom_comp_tensorHom := by
      intro X₁ Y₁ Z₁ X₂ Y₂ Z₂ f₁ f₂ g₁ g₂
      obtain ⟨f₁⟩ := f₁
      obtain ⟨f₂⟩ := f₂
      obtain ⟨g₁⟩ := g₁
      obtain ⟨g₂⟩ := g₂
      exact Quotient.sound (.monoidal (.interchange f₁ f₂ g₁ g₂)))
    (associator_naturality := by
      intro X₁ X₂ X₃ Y₁ Y₂ Y₃ f₁ f₂ f₃
      obtain ⟨f₁⟩ := f₁
      obtain ⟨f₂⟩ := f₂
      obtain ⟨f₃⟩ := f₃
      rw [associator_hom_class Y₁ Y₂ Y₃, associator_hom_class X₁ X₂ X₃]
      exact Quotient.sound (.monoidal (.associator_naturality f₁ f₂ f₃)))
    (leftUnitor_naturality := by
      intro X Y f
      obtain ⟨f⟩ := f
      rw [leftUnitor_hom_class Y, leftUnitor_hom_class X]
      exact Quotient.sound (.monoidal (.leftUnitor_naturality f)))
    (rightUnitor_naturality := by
      intro X Y f
      obtain ⟨f⟩ := f
      rw [rightUnitor_hom_class Y, rightUnitor_hom_class X]
      exact Quotient.sound (.monoidal (.rightUnitor_naturality f)))
    (pentagon := pentagon_transport)
    (triangle := triangle_transport)

/-- Composition of representative classes is represented by raw composition. -/
@[simp] theorem comp_mk {a b c : ℕ} (f : Cob2Mor a b) (g : Cob2Mor b c) :
    qcomp (⟦f⟧ : Cob2SymmetricHom ⟨a⟩ ⟨b⟩)
      (⟦g⟧ : Cob2SymmetricHom ⟨b⟩ ⟨c⟩) =
        (⟦Cob2Mor.comp f g⟧ : Cob2SymmetricHom ⟨a⟩ ⟨c⟩) := rfl

/-- Tensor of representative classes is represented by raw tensor. -/
@[simp] theorem tensor_mk {a b c d : ℕ} (f : Cob2Mor a b) (g : Cob2Mor c d) :
    tensorHom (⟦f⟧ : Cob2SymmetricHom ⟨a⟩ ⟨b⟩)
      (⟦g⟧ : Cob2SymmetricHom ⟨c⟩ ⟨d⟩) =
        (⟦Cob2Mor.tensor f g⟧ : Cob2SymmetricHom ⟨a + c⟩ ⟨b + d⟩) := rfl

/-- The inverse associator is represented by the raw inverse transport. -/
theorem associator_inv_class (X Y Z : Cob2SymmetricObj) :
    (α_ X Y Z).inv =
      (⟦cob2αmInv X.arity Y.arity Z.arity⟧ :
        tensorObj X (tensorObj Y Z) ⟶ tensorObj (tensorObj X Y) Z) := by
  change eqToHom (assocEq X Y Z).symm = _
  convert (class_eqToMor (Nat.add_assoc X.arity Y.arity Z.arity).symm).symm

/-- The braiding is the class of the existing raw swap generator. -/
def cob2Braiding (X Y : Cob2SymmetricObj) : X ⊗ Y ≅ Y ⊗ X where
  hom := ⟦Cob2Mor.swap X.arity Y.arity⟧
  inv := ⟦Cob2Mor.swap Y.arity X.arity⟧
  hom_inv_id := Quotient.sound (.swap_involutive X.arity Y.arity)
  inv_hom_id := Quotient.sound (.swap_involutive Y.arity X.arity)

/-- The braiding hom is literally represented by the raw swap word. -/
@[simp] theorem braiding_hom_class (X Y : Cob2SymmetricObj) :
    (cob2Braiding X Y).hom = ⟦Cob2Mor.swap X.arity Y.arity⟧ := rfl

/-- Joint naturality of the raw swap classes. -/
theorem swap_naturality {X X' Y Y' : Cob2SymmetricObj}
    (f : X ⟶ X') (g : Y ⟶ Y') :
    (f ⊗ₘ g) ≫ (cob2Braiding X' Y').hom =
      (cob2Braiding X Y).hom ≫ (g ⊗ₘ f) := by
  obtain ⟨f⟩ := f
  obtain ⟨g⟩ := g
  exact Quotient.sound (.swap_naturality f g)

/-- The raw swap class is involutive. -/
theorem swap_involutive (X Y : Cob2SymmetricObj) :
    (cob2Braiding X Y).hom ≫ (cob2Braiding Y X).hom = 𝟙 (X ⊗ Y) :=
  Quotient.sound (.swap_involutive X.arity Y.arity)

/-- Both braided hexagons and naturality descend directly from the defining relations. -/
instance cob2BraidedCategory : BraidedCategory Cob2SymmetricObj where
  braiding := cob2Braiding
  braiding_naturality_left := by
    intro X Y f Z
    obtain ⟨f⟩ := f
    exact Quotient.sound (.swap_naturality f (.id Z.arity))
  braiding_naturality_right := by
    intro X Y Z f
    obtain ⟨f⟩ := f
    exact Quotient.sound (.swap_naturality (.id X.arity) f)
  hexagon_forward := by
    intro X Y Z
    rw [associator_hom_class, associator_hom_class, associator_hom_class]
    let a := X.arity; let b := Y.arity; let c := Z.arity
    have h :
        (⟦Cob2Mor.comp (Cob2Mor.comp (cob2αm a b c) (.swap a (b + c)))
            (cob2αm b c a)⟧ : Cob2SymmetricHom ⟨(a + b) + c⟩ ⟨b + (c + a)⟩) =
          ⟦Cob2Mor.comp (Cob2Mor.comp (.tensor (.swap a b) (.id c)) (cob2αm b a c))
            (.tensor (.id b) (.swap a c))⟧ :=
      Quotient.sound (Cob2SymmetricRel.hexagon_forward a b c)
    simp only [← Category.assoc]
    dsimp only [CategoryStruct.comp, CategoryStruct.id,
      MonoidalCategoryStruct.whiskerLeft, MonoidalCategoryStruct.whiskerRight, cob2Braiding,
      qcomp, qid, tensorHom]
    exact h
  hexagon_reverse := by
    intro X Y Z
    rw [associator_inv_class, associator_inv_class, associator_inv_class]
    let a := X.arity; let b := Y.arity; let c := Z.arity
    have h :
        (⟦Cob2Mor.comp (Cob2Mor.comp (cob2αmInv a b c) (.swap (a + b) c))
            (cob2αmInv c a b)⟧ : Cob2SymmetricHom ⟨a + (b + c)⟩ ⟨(c + a) + b⟩) =
          ⟦Cob2Mor.comp (Cob2Mor.comp (.tensor (.id a) (.swap b c)) (cob2αmInv a c b))
            (.tensor (.swap a c) (.id b))⟧ :=
      Quotient.sound (Cob2SymmetricRel.hexagon_reverse a b c)
    simp only [← Category.assoc]
    dsimp only [CategoryStruct.comp, CategoryStruct.id,
      MonoidalCategoryStruct.whiskerLeft, MonoidalCategoryStruct.whiskerRight, cob2Braiding,
      qcomp, qid, tensorHom]
    exact h

/-- The forward hexagon for raw swap classes. -/
theorem swap_hexagon_forward (X Y Z : Cob2SymmetricObj) :
    (α_ X Y Z).hom ≫ (β_ X (Y ⊗ Z)).hom ≫ (α_ Y Z X).hom =
      ((β_ X Y).hom ▷ Z) ≫ (α_ Y X Z).hom ≫ (Y ◁ (β_ X Z).hom) :=
  BraidedCategory.hexagon_forward X Y Z

/-- The reverse hexagon for raw swap classes. -/
theorem swap_hexagon_reverse (X Y Z : Cob2SymmetricObj) :
    (α_ X Y Z).inv ≫ (β_ (X ⊗ Y) Z).hom ≫ (α_ Z X Y).inv =
      (X ◁ (β_ Y Z).hom) ≫ (α_ X Z Y).inv ≫ ((β_ X Z).hom ▷ Y) :=
  BraidedCategory.hexagon_reverse X Y Z

/-- Involutivity upgrades the braided quotient to a symmetric monoidal category. -/
instance cob2SymmetricCategory : SymmetricCategory Cob2SymmetricObj where
  symmetry := swap_involutive

/-- Named symmetry theorem. -/
theorem swap_symmetry (X Y : Cob2SymmetricObj) :
    (β_ X Y).hom ≫ (β_ Y X).hom = 𝟙 (X ⊗ Y) :=
  SymmetricCategory.symmetry X Y

/-- Interchange smoke theorem. -/
theorem cob2Symmetric_interchange
    {X₁ Y₁ Z₁ X₂ Y₂ Z₂ : Cob2SymmetricObj}
    (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂)
    (g₁ : Y₁ ⟶ Z₁) (g₂ : Y₂ ⟶ Z₂) :
    (f₁ ⊗ₘ f₂) ≫ (g₁ ⊗ₘ g₂) = (f₁ ≫ g₁) ⊗ₘ (f₂ ≫ g₂) :=
  MonoidalCategory.tensorHom_comp_tensorHom _ _ _ _

/-- Associator-naturality smoke theorem. -/
theorem cob2Symmetric_associator_naturality
    {X₁ X₂ X₃ Y₁ Y₂ Y₃ : Cob2SymmetricObj}
    (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂) (f₃ : X₃ ⟶ Y₃) :
    ((f₁ ⊗ₘ f₂) ⊗ₘ f₃) ≫ (α_ Y₁ Y₂ Y₃).hom =
      (α_ X₁ X₂ X₃).hom ≫ (f₁ ⊗ₘ (f₂ ⊗ₘ f₃)) :=
  MonoidalCategory.associator_naturality _ _ _

end Cob2Symmetric

/-- The canonical quotient functor from the monoidal rung. -/
def Cob2Monoidal.toSymmetricQuotient : Cob2MonoidalObj ⥤ Cob2SymmetricObj where
  obj X := ⟨X.arity⟩
  map f := Quotient.map (fun w => w) (fun _ _ h => by
    change Cob2MonoidalRel _ _ at h
    exact Cob2SymmetricRel.monoidal h) f
  map_id _ := rfl
  map_comp f g := by obtain ⟨f⟩ := f; obtain ⟨g⟩ := g; rfl

namespace CommFrobeniusData

variable {C : Type*} [Category C] [MonoidalCategory C] [SymmetricCategory C]

/-- Interpretation of a swap is the target braiding conjugated by `powAdd`. -/
theorem interpret_swap (A : CommFrobeniusData C) (a b : ℕ) :
    A.interpret (.swap a b) =
      (A.powAdd a b).hom ≫ (β_ (A.objPow a) (A.objPow b)).hom ≫
        (A.powAdd b a).inv := rfl

/-- Raw swap is natural under the Frobenius interpretation. -/
theorem interpret_swap_naturality (A : CommFrobeniusData C)
    {a b c d : ℕ} (f : Cob2Mor a b) (g : Cob2Mor c d) :
    A.interpret (.comp (.tensor f g) (.swap b d)) =
      A.interpret (.comp (.swap a c) (.tensor g f)) := by
  simp only [interpret_comp, interpret_tensor, interpret_swap, Category.assoc]
  rw [Iso.inv_hom_id_assoc, BraidedCategory.braiding_naturality_assoc]
  simp

/-- Raw swap is involutive in a symmetric target. -/
theorem interpret_swap_involutive (A : CommFrobeniusData C) (a b : ℕ) :
    A.interpret (.comp (.swap a b) (.swap b a)) = A.interpret (.id (a + b)) := by
  simp only [interpret_comp, interpret_swap, interpret_id, Category.assoc]
  rw [Iso.inv_hom_id_assoc, SymmetricCategory.symmetry_assoc]
  simp

/-- The raw forward hexagon is interpreted soundly. -/
theorem interpret_hexagon_forward (A : CommFrobeniusData C) (a b c : ℕ) :
    A.interpret
      (.comp (.comp (cob2αm a b c) (.swap a (b + c))) (cob2αm b c a)) =
    A.interpret
      (.comp (.comp (.tensor (.swap a b) (.id c)) (cob2αm b a c))
        (.tensor (.id b) (.swap a c))) := by
  simp only [interpret_comp, interpret_tensor, interpret_id, cob2αm,
    interpret_eqToMor, interpret_swap]
  simp only [MonoidalCategory.tensorHom_id, MonoidalCategory.id_tensorHom]
  -- First derive a useful lemma for eqToHom from powAdd_associativity
  have eqToHom_assoc : ∀ a b c : ℕ,
      eqToHom (congrArg A.objPow (Nat.add_assoc a b c)) =
        (A.powAdd (a + b) c).hom ≫
          (A.powAdd a b).hom ▷ A.objPow c ≫
            (α_ (A.objPow a) (A.objPow b) (A.objPow c)).hom ≫
              A.objPow a ◁ (A.powAdd b c).inv ≫ (A.powAdd a (b + c)).inv := by
    intro a b c
    have h := powAdd_associativity A a b c
    calc eqToHom _
        = ((A.powAdd (a + b) c).hom ≫ (A.powAdd a b).hom ▷ A.objPow c) ≫
          ((A.powAdd a b).inv ▷ A.objPow c ≫ (A.powAdd (a + b) c).inv ≫ eqToHom _) := by
          simp [Iso.hom_inv_id_assoc]
      _ = ((A.powAdd (a + b) c).hom ≫ (A.powAdd a b).hom ▷ A.objPow c) ≫
          ((α_ (A.objPow a) (A.objPow b) (A.objPow c)).hom ≫
            A.objPow a ◁ (A.powAdd b c).inv ≫ (A.powAdd a (b + c)).inv) := by rw [h]
      _ = _ := by simp [Category.assoc]
  rw [eqToHom_assoc a b c]
  rw [eqToHom_assoc b c a]
  rw [eqToHom_assoc b a c]
  simp [Category.assoc]

/-- The raw reverse hexagon is interpreted soundly. -/
theorem interpret_hexagon_reverse (A : CommFrobeniusData C) (a b c : ℕ) :
    A.interpret
      (.comp (.comp (cob2αmInv a b c) (.swap (a + b) c)) (cob2αmInv c a b)) =
    A.interpret
      (.comp (.comp (.tensor (.id a) (.swap b c)) (cob2αmInv a c b))
        (.tensor (.swap a c) (.id b))) := by
  simp only [interpret_comp, interpret_tensor, interpret_id, cob2αmInv,
    interpret_eqToMor, interpret_swap]
  simp only [MonoidalCategory.id_tensorHom, MonoidalCategory.tensorHom_id]
  have eqToHom_inv_assoc : ∀ a b c : ℕ,
      eqToHom (congrArg A.objPow (Nat.add_assoc a b c)).symm =
        (A.powAdd a (b + c)).hom ≫
          (A.objPow a ◁ (A.powAdd b c).hom) ≫
            (α_ (A.objPow a) (A.objPow b) (A.objPow c)).inv ≫
              (A.powAdd a b).inv ▷ A.objPow c ≫ (A.powAdd (a + b) c).inv := by
    intro a b c
    have h : eqToHom (congrArg A.objPow (Nat.add_assoc a b c)).symm ≫
        (A.powAdd (a + b) c).hom ≫ ((A.powAdd a b).hom ▷ A.objPow c) =
      (A.powAdd a (b + c)).hom ≫ (A.objPow a ◁ (A.powAdd b c).hom) ≫
        (α_ (A.objPow a) (A.objPow b) (A.objPow c)).inv := by
      apply CategoryTheory.eq_of_inv_eq_inv
      simp only [IsIso.inv_comp, MonoidalCategory.inv_whiskerRight,
        MonoidalCategory.inv_whiskerLeft, CategoryTheory.inv_eqToHom,
        IsIso.Iso.inv_hom, IsIso.Iso.inv_inv, Category.assoc]
      exact powAdd_associativity A a b c
    have := h
    have h2 := congrArg (· ≫ (A.powAdd a b).inv ▷ A.objPow c ≫ (A.powAdd (a + b) c).inv) h
    simp [Category.assoc] at h2 ⊢
    exact h2
  rw [eqToHom_inv_assoc a b c]
  rw [eqToHom_inv_assoc c a b]
  rw [eqToHom_inv_assoc a c b]
  simp [Category.assoc]

/-- Every Frobenius interpretation into a symmetric target respects the symmetric relation. -/
theorem interpretSymmetric_sound (A : CommFrobeniusData C)
    {a b : ℕ} {f g : Cob2Mor a b} (h : Cob2SymmetricRel f g) :
    A.interpret f = A.interpret g := by
  induction h with
  | monoidal h => exact A.interpretMonoidal_sound h
  | comp_congr hf hg ihf ihg => simp only [interpret_comp]; rw [ihf, ihg]
  | tensor_congr hf hg ihf ihg => simp only [interpret_tensor]; rw [ihf, ihg]
  | refl f => rfl
  | symm h ih => exact ih.symm
  | trans hf hg ihf ihg => exact ihf.trans ihg
  | swap_naturality f g => exact A.interpret_swap_naturality f g
  | swap_involutive a b => exact A.interpret_swap_involutive a b
  | hexagon_forward a b c => exact A.interpret_hexagon_forward a b c
  | hexagon_reverse a b c => exact A.interpret_hexagon_reverse a b c

/-- The symmetric interpretation descended to quotient morphisms. -/
noncomputable def toCob2SymmetricFunctor (A : CommFrobeniusData C) :
    Cob2SymmetricObj ⥤ C where
  obj X := A.objPow X.arity
  map f := Quotient.lift (fun w => A.interpret w)
    (fun _ _ h => by
      change Cob2SymmetricRel _ _ at h
      exact A.interpretSymmetric_sound h) f
  map_id _ := rfl
  map_comp f g := by obtain ⟨f⟩ := f; obtain ⟨g⟩ := g; rfl

/-- Evaluation on a representative. -/
@[simp] theorem toCob2SymmetricFunctor_map_mk (A : CommFrobeniusData C)
    {a b : ℕ} (w : Cob2Mor a b) :
    A.toCob2SymmetricFunctor.map
      (⟦w⟧ : (⟨a⟩ : Cob2SymmetricObj) ⟶ ⟨b⟩) = A.interpret w := rfl

/-- The descended functor sends the source braiding to the interpreted raw swap. -/
theorem toCob2SymmetricFunctor_map_braiding (A : CommFrobeniusData C)
    (X Y : Cob2SymmetricObj) :
    A.toCob2SymmetricFunctor.map (β_ X Y).hom =
      (A.powAdd X.arity Y.arity).hom ≫
        (β_ (A.objPow X.arity) (A.objPow Y.arity)).hom ≫
          (A.powAdd Y.arity X.arity).inv := rfl

/-- Strong monoidal core, with tensorator `(powAdd).symm`. -/
noncomputable def toCob2SymmetricCore (A : CommFrobeniusData C) :
    A.toCob2SymmetricFunctor.CoreMonoidal where
  εIso := Iso.refl _
  μIso X Y := (A.powAdd X.arity Y.arity).symm
  μIso_hom_natural_left := by
    intro X Y f X'; obtain ⟨f⟩ := f
    change (A.interpret f ▷ A.objPow X'.arity) ≫ (A.powAdd Y.arity X'.arity).inv =
      (A.powAdd X.arity X'.arity).inv ≫ A.interpret (.tensor f (.id X'.arity))
    simp
  μIso_hom_natural_right := by
    intro X Y X' f; obtain ⟨f⟩ := f
    change (A.objPow X'.arity ◁ A.interpret f) ≫ (A.powAdd X'.arity Y.arity).inv =
      (A.powAdd X'.arity X.arity).inv ≫ A.interpret (.tensor (.id X'.arity) f)
    simp
  associativity := by
    intro X Y Z
    rw [Cob2Symmetric.associator_hom_class]
    change (A.powAdd X.arity Y.arity).inv ▷ A.objPow Z.arity ≫
      (A.powAdd (X.arity + Y.arity) Z.arity).inv ≫ A.interpret (cob2αm _ _ _) = _
    rw [cob2αm, CommFrobeniusData.interpret_eqToMor]
    convert A.powAdd_associativity X.arity Y.arity Z.arity
  left_unitality := by
    intro X
    rw [Cob2Symmetric.leftUnitor_hom_class]
    change (λ_ (A.objPow X.arity)).hom =
      (𝟙 (𝟙_ C) ▷ A.objPow X.arity) ≫ (A.powAdd 0 X.arity).inv ≫
        A.interpret (cob2Leftm X.arity)
    rw [cob2Leftm, CommFrobeniusData.interpret_eqToMor]
    simpa using A.powAdd_left_unitality X.arity
  right_unitality := by
    intro X
    rw [Cob2Symmetric.rightUnitor_hom_class]
    change (ρ_ (A.objPow X.arity)).hom =
      (A.objPow X.arity ◁ 𝟙 (𝟙_ C)) ≫ (A.powAdd X.arity 0).inv ≫
        A.interpret (cob2Rightm X.arity)
    rw [cob2Rightm, CommFrobeniusData.interpret_eqToMor]
    simp

/-- The descended interpretation is strong monoidal. -/
noncomputable def toCob2SymmetricFunctorMonoidal (A : CommFrobeniusData C) :
    A.toCob2SymmetricFunctor.Monoidal := A.toCob2SymmetricCore.toMonoidal

/-- Exact braided compatibility of the strong tensorator. -/
theorem toCob2SymmetricFunctor_braided (A : CommFrobeniusData C)
    (X Y : Cob2SymmetricObj) :
    (A.powAdd X.arity Y.arity).inv ≫ A.toCob2SymmetricFunctor.map (β_ X Y).hom =
      (β_ (A.toCob2SymmetricFunctor.obj X) (A.toCob2SymmetricFunctor.obj Y)).hom ≫
        (A.powAdd Y.arity X.arity).inv := by
  change (A.powAdd X.arity Y.arity).inv ≫
      ((A.powAdd X.arity Y.arity).hom ≫
        (β_ (A.objPow X.arity) (A.objPow Y.arity)).hom ≫
          (A.powAdd Y.arity X.arity).inv) =
    (β_ (A.objPow X.arity) (A.objPow Y.arity)).hom ≫
      (A.powAdd Y.arity X.arity).inv
  simp

/-- The descended strong monoidal interpretation is braided. -/
noncomputable def toCob2SymmetricFunctorBraided (A : CommFrobeniusData C) :
    A.toCob2SymmetricFunctor.Braided := by
  letI := A.toCob2SymmetricFunctorMonoidal
  refine { braided := ?_ }
  intro X Y
  exact A.toCob2SymmetricFunctor_braided X Y

/-- The packaged symmetric algebraic TQFT. -/
noncomputable def toSymmetricTQFT2d (A : CommFrobeniusData C) :
    TQFT2d Cob2SymmetricObj C where
  Z := A.toCob2SymmetricFunctor
  monoidal := A.toCob2SymmetricFunctorMonoidal
  braided := A.toCob2SymmetricFunctorBraided

/-- Passing through the symmetric quotient recovers the monoidal interpretation. -/
theorem toCob2SymmetricFunctor_comp_toSymmetricQuotient (A : CommFrobeniusData C) :
    Cob2Monoidal.toSymmetricQuotient ⋙ A.toCob2SymmetricFunctor =
      A.toCob2MonoidalFunctor := by
  refine CategoryTheory.Functor.ext (fun _ => rfl) ?_
  intro X Y f
  simp only [eqToHom_refl, Category.id_comp, Category.comp_id]
  induction f using Quotient.inductionOn
  rfl

end CommFrobeniusData
