import RequestProject.Cob2SurfaceComposition
import Mathlib.Combinatorics.SimpleGraph.Acyclic

/-!
# The Euler bound for surface-code gluing components

The component quotient used by `SurfaceCode.comp` is generated by a finite
bipartite multigraph.  This file forgets parallel-edge multiplicities long
enough to apply the standard connected-simple-graph Euler bound, then maps
the retained indexed middle circles onto the resulting simple edge set.
Consequently every gluing component satisfies

`vertexCount ≤ edgeCount + 1`.

This shows that the natural-number subtraction in the gluing genus is never
truncated and isolates its graph-cycle contribution.
-/

noncomputable section

namespace Cob2NormalForm

namespace SurfaceCode

open SimpleGraph

variable {a b c : ℕ} (s : SurfaceCode a b) (t : SurfaceCode b c)

/-- The old component vertices lying over one resulting gluing component. -/
abbrev GlueVertexFiber (q : GlueComponent s t) :=
  {v : GlueVertex s t // vertexComponent s t v = q}

/-- The simple graph underlying one gluing component.  Its vertices are the
old components in the fiber, and two vertices are adjacent when at least one
indexed middle circle joins them.  Parallel indexed circles therefore yield
one simple edge here, but remain distinct in `edgeCount`. -/
def glueFiberGraph (q : GlueComponent s t) :
    SimpleGraph (GlueVertexFiber s t q) :=
  SimpleGraph.fromRel fun x y => GlueStep s t x.1 y.1

private theorem glueStep_ne {x y : GlueVertex s t}
    (h : GlueStep s t x y) : x ≠ y := by
  rintro rfl
  rcases h with ⟨i, h⟩
  have hx : x = Sum.inl (s.outComp i) := congrArg Prod.fst h
  have hy : x = Sum.inr (t.inComp i) := congrArg Prod.snd h
  have : False := by
    simpa using hx.symm.trans hy
  exact this

private theorem glueStep_adj
    (q : GlueComponent s t)
    {x y : GlueVertexFiber s t q}
    (h : GlueStep s t x.1 y.1) :
    (glueFiberGraph s t q).Adj x y := by
  change x ≠ y ∧
    (GlueStep s t x.1 y.1 ∨ GlueStep s t y.1 x.1)
  exact
    ⟨fun hxy => (glueStep_ne s t h) (congrArg Subtype.val hxy),
      Or.inl h⟩

private theorem eqvGen_glueStep_reachable
    {x y : GlueVertex s t}
    (h : Relation.EqvGen (GlueStep s t) x y) :
    ∀ (q : GlueComponent s t)
      (hx : vertexComponent s t x = q)
      (hy : vertexComponent s t y = q),
      (glueFiberGraph s t q).Reachable ⟨x, hx⟩ ⟨y, hy⟩ := by
  induction h with
  | rel x y hxy =>
      intro q hx hy
      exact (glueStep_adj s t q hxy).reachable
  | refl x =>
      intro q hx hy
      have hsub : (⟨x, hx⟩ : GlueVertexFiber s t q) = ⟨x, hy⟩ := by
        rfl
      rw [hsub]
  | symm x y _ ih =>
      intro q hx hy
      exact (ih q hy hx).symm
  | trans x y z hxy hyz ihxy ihyz =>
      intro q hx hz
      have hxyComp :
          vertexComponent s t x = vertexComponent s t y :=
        Quotient.sound hxy
      have hy : vertexComponent s t y = q := hxyComp.symm.trans hx
      exact (ihxy q hx hy).trans (ihyz q hy hz)

/-- The simple graph on the old vertices of a fixed gluing component is
connected. -/
theorem glueFiberGraph_connected (q : GlueComponent s t) :
    (glueFiberGraph s t q).Connected := by
  letI : Nonempty (GlueVertexFiber s t q) := by
    induction q using Quotient.inductionOn with
    | _ v => exact ⟨⟨v, rfl⟩⟩
  refine ⟨?_⟩
  intro x y
  apply eqvGen_glueStep_reachable s t
  exact Quotient.exact (x.2.trans y.2.symm)

/-- The indexed middle circles belonging to a fixed gluing component. -/
abbrev GlueEdgeFiber (q : GlueComponent s t) :=
  {i : Fin b //
    vertexComponent s t (Sum.inl (s.outComp i)) = q}

private def leftEdgeVertex
    (q : GlueComponent s t) (i : GlueEdgeFiber s t q) :
    GlueVertexFiber s t q :=
  ⟨Sum.inl (s.outComp i.1), i.2⟩

private def rightEdgeVertex
    (q : GlueComponent s t) (i : GlueEdgeFiber s t q) :
    GlueVertexFiber s t q :=
  ⟨Sum.inr (t.inComp i.1),
    (edgeEnds_same_component s t i.1).symm.trans i.2⟩

private theorem indexedEdge_adj
    (q : GlueComponent s t) (i : GlueEdgeFiber s t q) :
    (glueFiberGraph s t q).Adj
      (leftEdgeVertex s t q i) (rightEdgeVertex s t q i) := by
  apply glueStep_adj s t q
  exact ⟨i.1, rfl⟩

/-- Forget the multiplicity label of an indexed middle circle, retaining
only its edge in the underlying simple graph. -/
def indexedEdgeToSimpleEdge
    (q : GlueComponent s t) :
    GlueEdgeFiber s t q → (glueFiberGraph s t q).edgeSet :=
  fun i =>
    ⟨s(leftEdgeVertex s t q i, rightEdgeVertex s t q i),
      indexedEdge_adj s t q i⟩

private theorem indexedEdgeToSimpleEdge_surjective
    (q : GlueComponent s t) :
    Function.Surjective (indexedEdgeToSimpleEdge s t q) := by
  rintro ⟨e, he⟩
  induction e using Sym2.ind with
  | _ x y =>
      change (glueFiberGraph s t q).Adj x y at he
      change x ≠ y ∧
        (GlueStep s t x.1 y.1 ∨ GlueStep s t y.1 x.1) at he
      rcases he.2 with hxy | hyx
      · rcases hxy with ⟨i, hpair⟩
        have hx : x.1 = Sum.inl (s.outComp i) :=
          congrArg Prod.fst hpair
        have hy : y.1 = Sum.inr (t.inComp i) :=
          congrArg Prod.snd hpair
        let i' : GlueEdgeFiber s t q :=
          ⟨i, by simpa [hx] using x.2⟩
        refine ⟨i', ?_⟩
        apply Subtype.ext
        change s(leftEdgeVertex s t q i', rightEdgeVertex s t q i') =
          s(x, y)
        have hx' : leftEdgeVertex s t q i' = x := by
          apply Subtype.ext
          simpa [leftEdgeVertex] using hx.symm
        have hy' : rightEdgeVertex s t q i' = y := by
          apply Subtype.ext
          simpa [rightEdgeVertex] using hy.symm
        simp [hx', hy']
      · rcases hyx with ⟨i, hpair⟩
        have hy : y.1 = Sum.inl (s.outComp i) :=
          congrArg Prod.fst hpair
        have hx : x.1 = Sum.inr (t.inComp i) :=
          congrArg Prod.snd hpair
        let i' : GlueEdgeFiber s t q :=
          ⟨i, by simpa [hy] using y.2⟩
        refine ⟨i', ?_⟩
        apply Subtype.ext
        change s(leftEdgeVertex s t q i', rightEdgeVertex s t q i') =
          s(x, y)
        have hy' : leftEdgeVertex s t q i' = y := by
          apply Subtype.ext
          simpa [leftEdgeVertex] using hy.symm
        have hx' : rightEdgeVertex s t q i' = x := by
          apply Subtype.ext
          simpa [rightEdgeVertex] using hx.symm
        simp [hx', hy']

/-- Every gluing component has no more old vertices than indexed middle
circles plus one.  Parallel circles are retained on the right-hand side. -/
theorem vertexCount_le_edgeCount_add_one (q : GlueComponent s t) :
    vertexCount s t q ≤ edgeCount s t q + 1 := by
  have hsimple :
      Nat.card (glueFiberGraph s t q).edgeSet ≤
        Nat.card (GlueEdgeFiber s t q) :=
    Nat.card_le_card_of_surjective
      (indexedEdgeToSimpleEdge s t q)
      (indexedEdgeToSimpleEdge_surjective s t q)
  calc
    vertexCount s t q =
        Nat.card (GlueVertexFiber s t q) := rfl
    _ ≤ Nat.card (glueFiberGraph s t q).edgeSet + 1 :=
      (glueFiberGraph_connected s t q).card_vert_le_card_edgeSet_add_one
    _ ≤ Nat.card (GlueEdgeFiber s t q) + 1 :=
      Nat.add_le_add_right hsimple 1
    _ = edgeCount s t q + 1 := rfl

/-- The gluing genus is the old genus plus the nonnegative cycle rank.
The preceding Euler bound ensures that this rewrite does not hide truncated
subtraction. -/
theorem gluedGenus_eq_oldGenus_add_cycleRank
    (q : GlueComponent s t) :
    gluedGenus s t q =
      oldGenus s t q + (edgeCount s t q + 1 - vertexCount s t q) := by
  unfold gluedGenus
  have := vertexCount_le_edgeCount_add_one s t q
  omega

/-- The representative chosen by `SurfaceCode.comp` has one numeric label
for each component of the gluing quotient. -/
@[simp]
theorem comp_ncomp :
    (comp s t).ncomp = Nat.card (GlueComponent s t) :=
  by
    change
      @Fintype.card (GlueComponent s t) (glueComponentFintype s t) =
        Nat.card (GlueComponent s t)
    exact
      (@Nat.card_eq_fintype_card
        (GlueComponent s t) (glueComponentFintype s t)).symm

end SurfaceCode

end Cob2NormalForm
