/-
# A Frobenius Presentation Inspired by 2d Cobordisms

This file defines commutative Frobenius algebra data, raw generator syntax,
and an ordinary quotient category on natural-number objects. The identifiers
retain the historical `Cob2` name, but the current construction is not yet the
2-dimensional bordism category as a symmetric monoidal category.

## Mathematical Background and Scope

Classically, the oriented 2-dimensional bordism category is the free symmetric
monoidal category generated by a commutative Frobenius algebra. Establishing
that result here would require a monoidal category instance, tensor interchange,
symmetric coherence, and a free universal property. None of those is proved in
this file. The current development formalizes useful algebraic data and an
ordinary presentation category related to that theorem.
-/

import Mathlib

open CategoryTheory MonoidalCategory

noncomputable section

/-! ## Part 1: Commutative Frobenius Algebra in a Symmetric Monoidal Category

A commutative Frobenius algebra object in a symmetric monoidal category C
consists of:
- A monoid object (X, μ : X ⊗ X → X, η : 𝟙 → X)
- A comonoid object (X, δ : X → X ⊗ X, ε : X → 𝟙)
- The Frobenius relation: (μ ⊗ id) ∘ (id ⊗ δ) = δ ∘ μ = (id ⊗ μ) ∘ (δ ⊗ id)
- Commutativity: μ ∘ β_{X,X} = μ

We build on Mathlib's `MonObj` and `ComonObj` classes.
-/

/-- A Frobenius object in a monoidal category is an object with compatible
monoid and comonoid structures satisfying the Frobenius relation. -/
class FrobeniusObj {C : Type*} [Category C] [MonoidalCategory C]
    (X : C) extends MonObj X, ComonObj X where
  /-- Left Frobenius relation:
      (μ ⊗ id) ∘ (id ⊗ δ) = δ ∘ μ as maps X ⊗ X → X ⊗ X -/
  frobenius_left :
    (X ◁ ComonObj.comul) ≫ (α_ X X X).inv ≫ (MonObj.mul ▷ X) =
    MonObj.mul ≫ ComonObj.comul := by cat_disch
  /-- Right Frobenius relation:
      (id ⊗ μ) ∘ (δ ⊗ id) = δ ∘ μ as maps X ⊗ X → X ⊗ X -/
  frobenius_right :
    (ComonObj.comul ▷ X) ≫ (α_ X X X).hom ≫ (X ◁ MonObj.mul) =
    MonObj.mul ≫ ComonObj.comul := by cat_disch

/-- A commutative Frobenius object additionally satisfies commutativity
of the multiplication: μ ∘ β_{X,X} = μ -/
class CommFrobeniusObj {C : Type*} [Category C] [MonoidalCategory C]
    [BraidedCategory C] (X : C) extends FrobeniusObj X where
  /-- Commutativity: μ ∘ β = μ -/
  mul_comm : (β_ X X).hom ≫ MonObj.mul = MonObj.mul := by cat_disch

/-- A commutative Frobenius algebra in a symmetric monoidal category C. -/
structure CommFrobeniusAlgebra (C : Type*) [Category C] [MonoidalCategory C]
    [BraidedCategory C] where
  /-- The underlying object -/
  X : C
  /-- The commutative Frobenius structure -/
  [frobenius : CommFrobeniusObj X]

attribute [instance] CommFrobeniusAlgebra.frobenius

/-! ## Part 2: Explicit Data Record

For constructing concrete examples, we provide a plain data structure
rather than a typeclass. -/

/-- The data of a commutative Frobenius algebra in a monoidal category,
packaged as a single structure. This is the algebraic datum appearing in the
classical classification of 2d oriented TQFTs; that classification is not proved here. -/
structure CommFrobeniusData (C : Type*) [Category C] [MonoidalCategory C]
    [BraidedCategory C] where
  /-- The underlying object (the "state space" Z(S¹)) -/
  X : C
  /-- Multiplication: X ⊗ X → X (pair of pants) -/
  mul : X ⊗ X ⟶ X
  /-- Unit: 𝟙 → X (cap / birth of a circle) -/
  unit : 𝟙_ C ⟶ X
  /-- Comultiplication: X → X ⊗ X (copants / splitting of a circle) -/
  comul : X ⟶ X ⊗ X
  /-- Counit: X → 𝟙 (cup / death of a circle) -/
  counit : X ⟶ 𝟙_ C
  /-- Associativity of multiplication -/
  mul_assoc' : mul ▷ X ≫ mul = (α_ X X X).hom ≫ X ◁ mul ≫ mul := by cat_disch
  /-- Left unit law -/
  unit_mul : unit ▷ X ≫ mul = (λ_ X).hom := by cat_disch
  /-- Right unit law -/
  mul_unit : X ◁ unit ≫ mul = (ρ_ X).hom := by cat_disch
  /-- Coassociativity of comultiplication -/
  comul_coassoc' : comul ≫ X ◁ comul = comul ≫ comul ▷ X ≫ (α_ X X X).hom := by cat_disch
  /-- Left counit law -/
  counit_comul : comul ≫ counit ▷ X = (λ_ X).inv := by cat_disch
  /-- Right counit law -/
  comul_counit : comul ≫ X ◁ counit = (ρ_ X).inv := by cat_disch
  /-- Left Frobenius relation -/
  frobenius_left :
    (X ◁ comul) ≫ (α_ X X X).inv ≫ (mul ▷ X) = mul ≫ comul := by cat_disch
  /-- Right Frobenius relation -/
  frobenius_right :
    (comul ▷ X) ≫ (α_ X X X).hom ≫ (X ◁ mul) = mul ≫ comul := by cat_disch
  /-- Commutativity of multiplication -/
  mul_comm' : (β_ X X).hom ≫ mul = mul := by cat_disch

/-- Convert a `CommFrobeniusData` to a `CommFrobeniusAlgebra`. -/
def CommFrobeniusData.toAlgebra {C : Type*} [Category C] [MonoidalCategory C]
    [BraidedCategory C] (A : CommFrobeniusData C) : CommFrobeniusAlgebra C where
  X := A.X
  frobenius :=
    { mul := A.mul
      one := A.unit
      mul_assoc := A.mul_assoc'
      one_mul := A.unit_mul
      mul_one := A.mul_unit
      comul := A.comul
      counit := A.counit
      counit_comul := A.counit_comul
      comul_counit := A.comul_counit
      comul_assoc := A.comul_coassoc'
      frobenius_left := A.frobenius_left
      frobenius_right := A.frobenius_right
      mul_comm := A.mul_comm' }

/-! ## Part 3: The Trivial Frobenius Algebra

The unit object 𝟙_ C carries a canonical commutative Frobenius algebra
structure. Under the classical classification, this datum corresponds to the
trivial 2d TQFT; the correspondence itself is not constructed here. -/

/-- The unit object 𝟙_ C carries a canonical commutative Frobenius
algebra structure. -/
def trivialFrobenius (C : Type*) [Category C] [MonoidalCategory C]
    [BraidedCategory C] : CommFrobeniusData C where
  X := 𝟙_ C
  mul := (λ_ (𝟙_ C)).hom
  unit := 𝟙 (𝟙_ C)
  comul := (λ_ (𝟙_ C)).inv
  counit := 𝟙 (𝟙_ C)
  mul_assoc' := by coherence
  unit_mul := by coherence
  mul_unit := by coherence
  comul_coassoc' := by coherence
  counit_comul := by coherence
  comul_counit := by coherence
  frobenius_left := by coherence
  frobenius_right := by coherence
  mul_comm' := by
    rw [braiding_tensorUnit_right, Category.assoc, Iso.inv_hom_id, Category.comp_id,
        unitors_equal]

/-! ## Part 4: A Frobenius generators-and-relations presentation

Objects are natural numbers. Raw morphisms are generated by the four Frobenius
operations together with identity, composition, a formal tensor constructor,
and swaps. The quotient below produces an ordinary category. A monoidal or
symmetric category structure and completeness for geometric cobordisms are not
yet established.
-/

/-- Raw syntax generated by the four Frobenius operations and closed under
formal composition, tensor, and swap constructors. -/
inductive Cob2Mor : ℕ → ℕ → Type
  | id (n : ℕ) : Cob2Mor n n
  | μ : Cob2Mor 2 1                    -- multiplication (pair of pants)
  | η : Cob2Mor 0 1                    -- unit (cap)
  | δ : Cob2Mor 1 2                    -- comultiplication (copants)
  | ε : Cob2Mor 1 0                    -- counit (cup)
  | comp {a b c : ℕ} : Cob2Mor a b → Cob2Mor b c → Cob2Mor a c
  | tensor {a b c d : ℕ} : Cob2Mor a b → Cob2Mor c d → Cob2Mor (a + c) (b + d)
  | swap (a b : ℕ) : Cob2Mor (a + b) (b + a) -- symmetric braiding

/-- The relation on `Cob2Mor` imposing the commutative Frobenius algebra
axioms. No theorem proves that this relation is complete for geometric
2-dimensional cobordisms.

Note: We provide explicit type parameters `(a := ...) (c := ...)` to
`tensor` to help Lean's unifier match `n + m` with concrete numerals. -/
inductive Cob2Rel : {a b : ℕ} → Cob2Mor a b → Cob2Mor a b → Prop
  -- Category axioms
  | id_comp {a b : ℕ} (f : Cob2Mor a b) :
      Cob2Rel (.comp (.id a) f) f
  | comp_id {a b : ℕ} (f : Cob2Mor a b) :
      Cob2Rel (.comp f (.id b)) f
  | assoc {a b c d : ℕ} (f : Cob2Mor a b) (g : Cob2Mor b c) (h : Cob2Mor c d) :
      Cob2Rel (.comp (.comp f g) h) (.comp f (.comp g h))
  -- Monoid axioms
  -- μ ∘ (μ ⊗ id₁) = μ ∘ (id₁ ⊗ μ) : 3 → 1
  | mul_assoc :
      Cob2Rel (.comp (.tensor (a := 2) (c := 1) .μ (.id 1)) .μ)
              (.comp (.tensor (a := 1) (c := 2) (.id 1) .μ) .μ)
  -- μ ∘ (η ⊗ id₁) = id₁ : 1 → 1
  | unit_left :
      Cob2Rel (.comp (.tensor (a := 0) (c := 1) .η (.id 1)) .μ) (.id 1)
  -- μ ∘ (id₁ ⊗ η) = id₁ : 1 → 1
  | unit_right :
      Cob2Rel (.comp (.tensor (a := 1) (c := 0) (.id 1) .η) .μ) (.id 1)
  -- Comonoid axioms
  -- (δ ⊗ id₁) ∘ δ = (id₁ ⊗ δ) ∘ δ : 1 → 3
  | comul_coassoc :
      Cob2Rel (.comp .δ (.tensor (a := 1) (c := 1) (b := 2) (d := 1) .δ (.id 1)))
              (.comp .δ (.tensor (a := 1) (c := 1) (b := 1) (d := 2) (.id 1) .δ))
  -- (ε ⊗ id₁) ∘ δ = id₁ : 1 → 1
  | counit_left :
      Cob2Rel (.comp .δ (.tensor (a := 1) (c := 1) (b := 0) (d := 1) .ε (.id 1))) (.id 1)
  -- (id₁ ⊗ ε) ∘ δ = id₁ : 1 → 1
  | counit_right :
      Cob2Rel (.comp .δ (.tensor (a := 1) (c := 1) (b := 1) (d := 0) (.id 1) .ε)) (.id 1)
  -- Frobenius relation: (μ ⊗ id₁) ∘ (id₁ ⊗ δ) = δ ∘ μ : 2 → 2
  | frobenius :
      Cob2Rel (.comp (.tensor (a := 1) (c := 1) (b := 1) (d := 2) (.id 1) .δ)
                     (.tensor (a := 2) (c := 1) (b := 1) (d := 1) .μ (.id 1)))
              (.comp .μ .δ)
  -- Commutativity: μ ∘ swap = μ : 2 → 1
  | mul_comm :
      Cob2Rel (.comp (.swap 1 1) .μ) .μ
  -- Congruence rules
  | comp_congr {a b c : ℕ} {f f' : Cob2Mor a b} {g g' : Cob2Mor b c} :
      Cob2Rel f f' → Cob2Rel g g' → Cob2Rel (.comp f g) (.comp f' g')
  | tensor_congr {a b c d : ℕ} {f f' : Cob2Mor a b} {g g' : Cob2Mor c d} :
      Cob2Rel f f' → Cob2Rel g g' → Cob2Rel (.tensor f g) (.tensor f' g')
  -- Equivalence relation
  | refl {a b : ℕ} (f : Cob2Mor a b) : Cob2Rel f f
  | symm {a b : ℕ} {f g : Cob2Mor a b} : Cob2Rel f g → Cob2Rel g f
  | trans {a b : ℕ} {f g h : Cob2Mor a b} : Cob2Rel f g → Cob2Rel g h → Cob2Rel f h

/-- The setoid on `Cob2Mor a b` induced by `Cob2Rel`. -/
instance Cob2Setoid (a b : ℕ) : Setoid (Cob2Mor a b) where
  r := Cob2Rel
  iseqv := ⟨Cob2Rel.refl, fun h => Cob2Rel.symm h, fun h1 h2 => Cob2Rel.trans h1 h2⟩

/-- Morphisms in the ordinary Frobenius presentation category: equivalence classes of
raw generator words modulo the selected relations. -/
def Cob2Hom (a b : ℕ) : Type := Quotient (Cob2Setoid a b)

namespace Cob2

/-- Identity morphism in Cob2. -/
def id (n : ℕ) : Cob2Hom n n := ⟦Cob2Mor.id n⟧

/-- Composition in Cob2. -/
def comp {a b c : ℕ} (f : Cob2Hom a b) (g : Cob2Hom b c) : Cob2Hom a c :=
  Quotient.lift₂ (fun f g => ⟦Cob2Mor.comp f g⟧)
    (fun _ _ _ _ h1 h2 => Quotient.sound (Cob2Rel.comp_congr h1 h2)) f g

/-- Tensor product of morphisms in Cob2. -/
def tensor {a b c d : ℕ} (f : Cob2Hom a b) (g : Cob2Hom c d) :
    Cob2Hom (a + c) (b + d) :=
  Quotient.lift₂ (fun f g => ⟦Cob2Mor.tensor f g⟧)
    (fun _ _ _ _ h1 h2 => Quotient.sound (Cob2Rel.tensor_congr h1 h2)) f g

-- The four generators as Cob2Hom morphisms
/-- Multiplication: pair of pants, 2 → 1 -/
def mul : Cob2Hom 2 1 := ⟦Cob2Mor.μ⟧
/-- Unit: cap, 0 → 1 -/
def unit : Cob2Hom 0 1 := ⟦Cob2Mor.η⟧
/-- Comultiplication: copants, 1 → 2 -/
def comul : Cob2Hom 1 2 := ⟦Cob2Mor.δ⟧
/-- Counit: cup, 1 → 0 -/
def counit : Cob2Hom 1 0 := ⟦Cob2Mor.ε⟧
/-- Swap: braiding, a + b → b + a -/
def swap (a b : ℕ) : Cob2Hom (a + b) (b + a) := ⟦Cob2Mor.swap a b⟧

end Cob2

/-- The ordinary category underlying the current Frobenius presentation.
It is not yet equipped with the monoidal and symmetric instances required of `2Cob`. -/
instance Cob2Category : Category ℕ where
  Hom := Cob2Hom
  id := Cob2.id
  comp := Cob2.comp
  id_comp f := by
    obtain ⟨f⟩ := f
    exact Quotient.sound (Cob2Rel.id_comp f)
  comp_id f := by
    obtain ⟨f⟩ := f
    exact Quotient.sound (Cob2Rel.comp_id f)
  assoc f g h := by
    obtain ⟨f⟩ := f; obtain ⟨g⟩ := g; obtain ⟨h⟩ := h
    exact Quotient.sound (Cob2Rel.assoc f g h)

/-- Historical notation for the ordinary Frobenius presentation category. -/
abbrev Cob2Cat := ℕ

/-! ## Part 5: Abstract braided-monoidal scaffolding

This duplicates the abstract structure from `LiquidTQFT.lean`. It is not a
standard 2d TQFT definition because the source is arbitrary and braided rather
than an actual symmetric monoidal bordism category.
-/

/-- An abstract braided monoidal theory `Z : S ⥤ C`. -/
structure TQFT2d
    (S : Type*) [Category S] [MonoidalCategory S] [BraidedCategory S]
    (C : Type*) [Category C] [MonoidalCategory C] [BraidedCategory C] where
  /-- The underlying functor -/
  Z : S ⥤ C
  /-- The monoidal structure on Z -/
  monoidal : Z.Monoidal
  /-- Z respects braidings -/
  braided : Z.Braided

/-- Composition with a braided monoidal functor preserves this abstract
braided-monoidal theory structure. -/
def TQFT2d.transfer
    {S : Type*} [Category S] [MonoidalCategory S] [BraidedCategory S]
    {C : Type*} [Category C] [MonoidalCategory C] [BraidedCategory C]
    {D : Type*} [Category D] [MonoidalCategory D] [BraidedCategory D]
    (T : TQFT2d S C)
    (F : C ⥤ D) [hF : F.Monoidal] [hFb : F.Braided] :
    TQFT2d S D where
  Z := T.Z ⋙ F
  monoidal := by letI := T.monoidal; infer_instance
  braided := by letI := T.monoidal; letI := T.braided; infer_instance

/-! ## Part 6: An unfinished ordinary functor

The classical classification theorem concerns symmetric monoidal functors from
the genuine category `2Cob`. The current source has no monoidal or symmetric
instance, so the unfinished definition below would construct only an ordinary
functor from the presentation category.
-/

/-- Intended ordinary functor from the Frobenius presentation category.
The object assignment sends `n` to `X^⊗n`; the morphism action and functoriality
proofs remain placeholders. Even when completed, symmetric monoidality and the
classification universal property would still require separate proofs. -/
def CommFrobeniusData.toCob2Functor {C : Type*} [Category C] [MonoidalCategory C]
    [BraidedCategory C] (A : CommFrobeniusData C) :
    Cob2Cat ⥤ C where
  obj n := Nat.recOn n (𝟙_ C) (fun k ih => ih ⊗ A.X)
  map := sorry -- Requires matching on the quotient and verifying
               -- well-definedness from Frobenius relations
  map_id := sorry
  map_comp := sorry

/-! ## Summary

### Fully formalized (no sorry):
1. ✅ `FrobeniusObj` - Frobenius object typeclass (monoid + comonoid + Frobenius relation)
2. ✅ `CommFrobeniusObj` - commutative Frobenius object typeclass
3. ✅ `CommFrobeniusAlgebra` - bundled commutative Frobenius algebra
4. ✅ `CommFrobeniusData` - explicit data record for Frobenius algebras
5. ✅ `CommFrobeniusData.toAlgebra` - conversion from data to typeclass
6. ✅ `Cob2Mor` - raw Frobenius generator syntax
7. ✅ `Cob2Rel` - selected Frobenius and category relations
8. ✅ `Cob2Hom` - quotient morphisms of the presentation
9. ✅ `Cob2Category` - ordinary `Category ℕ` instance; no monoidal structure
10. ✅ `TQFT2d` - abstract braided monoidal theory data
11. ✅ `TQFT2d.transfer` - composition of braided monoidal functors
12. ✅ `trivialFrobenius` - unit object as trivial Frobenius algebra (fully proved)

### Uses sorry:
- `CommFrobeniusData.toCob2Functor` - an unfinished ordinary functor;
  completing it would not yet establish symmetric monoidality or the classification theorem

### Connection to LiquidTQFT.lean:
- `TQFT2d` mirrors `AbstractTQFT` from LiquidTQFT.lean
- `TQFT2d.transfer` mirrors `AbstractTQFT.transfer`
- A braided monoidal functor `F : C → CondensedAb` transfers the abstract
  braided-monoidal structure; applying this to a genuine TQFT requires further constructions
-/

end